/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Viewers;

import java.awt.Color;
import Controllers.EstudanteController;
import Controllers.AvaliacaoController;
import ModelsBean.Avaliacao;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controllers.DisciplinaController;
import Controllers.NotaController;
import ModelsBean.Estudante;
import ModelsBean.Nota;

/**
 *
 * @author Mr. Savagery
 */
public class TeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TeacherDashboard
     */
    public TeacherDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userLogo = new javax.swing.JLabel();
        sairTab = new javax.swing.JPanel();
        sair = new java.awt.Label();
        sairIcon = new javax.swing.JLabel();
        savaLife = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atualizarLista = new javax.swing.JButton();
        EstJScrollPane = new javax.swing.JScrollPane();
        estTable = new javax.swing.JTable();
        avalTab = new javax.swing.JPanel();
        avaliacoes = new java.awt.Label();
        avalIcon = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        atualizarLista3 = new javax.swing.JButton();
        EstJScrollPane3 = new javax.swing.JScrollPane();
        avalTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        efectuarAvalBtn = new javax.swing.JButton();
        atualizarAvalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(933, 529));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        userLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/verified_account_100px.png"))); // NOI18N

        sairTab.setBackground(new java.awt.Color(0, 51, 153));

        sair.setBackground(new java.awt.Color(0, 51, 153));
        sair.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairMouseExited(evt);
            }
        });

        sairIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sairIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shutdown_41px.png"))); // NOI18N
        sairIcon.setToolTipText("");
        sairIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sairTabLayout = new javax.swing.GroupLayout(sairTab);
        sairTab.setLayout(sairTabLayout);
        sairTabLayout.setHorizontalGroup(
            sairTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sairTabLayout.createSequentialGroup()
                .addComponent(sairIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sairTabLayout.setVerticalGroup(
            sairTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(sairIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        savaLife.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        savaLife.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savaLife.setText("SavageryLife@gmail.com");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("<html>Entao, Voces vao querer clones \n com ou sem Susano'o?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savaLife, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sairTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savaLife, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE ESTUDANTES");
        jLabel1.setPreferredSize(new java.awt.Dimension(142, 19));

        atualizarLista.setBackground(new java.awt.Color(153, 153, 255));
        atualizarLista.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        atualizarLista.setForeground(new java.awt.Color(0, 0, 0));
        atualizarLista.setText("Atualizar Lista");
        atualizarLista.setPreferredSize(new java.awt.Dimension(122, 19));
        atualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(atualizarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizarLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        estTable.setBackground(new java.awt.Color(204, 204, 255));
        estTable.setForeground(new java.awt.Color(0, 0, 0));
        estTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Genero", "Ano de Ingresso"
            }
        ));
        EstJScrollPane.setViewportView(estTable);

        avalTab.setBackground(new java.awt.Color(0, 51, 153));
        avalTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avalTabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avalTabMouseExited(evt);
            }
        });

        avaliacoes.setBackground(new java.awt.Color(0, 51, 153));
        avaliacoes.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        avaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        avaliacoes.setText("Minhas Avaliacoes");
        avaliacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avaliacoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avaliacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avaliacoesMouseExited(evt);
            }
        });

        avalIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/todo_list_41px.png"))); // NOI18N
        avalIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avalIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avalIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avalIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout avalTabLayout = new javax.swing.GroupLayout(avalTab);
        avalTab.setLayout(avalTabLayout);
        avalTabLayout.setHorizontalGroup(
            avalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avalTabLayout.createSequentialGroup()
                .addComponent(avalIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avaliacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        avalTabLayout.setVerticalGroup(
            avalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avaliacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(avalIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LISTA DAS AVALIACOES EFECTUADAS");
        jLabel4.setPreferredSize(new java.awt.Dimension(142, 19));

        atualizarLista3.setBackground(new java.awt.Color(153, 153, 255));
        atualizarLista3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        atualizarLista3.setForeground(new java.awt.Color(0, 0, 0));
        atualizarLista3.setText("Atualizar Lista");
        atualizarLista3.setPreferredSize(new java.awt.Dimension(122, 19));
        atualizarLista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLista3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(atualizarLista3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizarLista3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        avalTable.setBackground(new java.awt.Color(204, 204, 255));
        avalTable.setForeground(new java.awt.Color(0, 0, 0));
        avalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Avaliacao", "Data", "Disciplina", "Nota", "Nome do estudante"
            }
        ));
        EstJScrollPane3.setViewportView(avalTable);

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));

        efectuarAvalBtn.setBackground(new java.awt.Color(0, 0, 102));
        efectuarAvalBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        efectuarAvalBtn.setForeground(new java.awt.Color(255, 255, 255));
        efectuarAvalBtn.setText("EFECTUAR AVALIACAO");
        efectuarAvalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectuarAvalBtnActionPerformed(evt);
            }
        });

        atualizarAvalBtn.setBackground(new java.awt.Color(0, 0, 102));
        atualizarAvalBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atualizarAvalBtn.setForeground(new java.awt.Color(255, 255, 255));
        atualizarAvalBtn.setText("ACTUALIZAR AVALIACAO");
        atualizarAvalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAvalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(efectuarAvalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizarAvalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atualizarAvalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(efectuarAvalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EstJScrollPane)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avalTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EstJScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avalTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstJScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_sairMouseClicked

    private void sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseEntered
        sairTab.setBackground(new Color(51, 0, 102));
        sair.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_sairMouseEntered

    private void sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseExited
        sair.setBackground(new Color(0, 51, 153));
        sairTab.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_sairMouseExited

    private void sairIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairIconMouseEntered
        sairTab.setBackground(new Color(51, 0, 102));
        sair.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_sairIconMouseEntered

    private void sairIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairIconMouseExited
        sair.setBackground(new Color(0, 51, 153));
        sairTab.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_sairIconMouseExited
    
    public void fillTable(){
        try {
            DefaultTableModel modelo = (DefaultTableModel)estTable.getModel();
            modelo.setNumRows(0);
            EstudanteController estControl = new EstudanteController();
            for(int i = 0; i < estControl.showAll().size(); i++){
                String data[] = {String.valueOf(estControl.showAll().get(i).getCodigo()), estControl.showAll().get(i).getNome(),
                estControl.showAll().get(i).getGenero(), String.valueOf(estControl.showAll().get(i).getAnoIngresso())};
                DefaultTableModel model = (DefaultTableModel)estTable.getModel();
                model.addRow(data);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarListaActionPerformed
        try {
            fillTable();
            EstudanteController estControl = new EstudanteController();
            estControl.closeConnection();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizarListaActionPerformed

    private void avaliacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliacoesMouseClicked

    }//GEN-LAST:event_avaliacoesMouseClicked

    private void avaliacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliacoesMouseEntered
        avalTab.setBackground(new Color(51, 0, 102));
        avaliacoes.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_avaliacoesMouseEntered

    private void avaliacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliacoesMouseExited
        avalTab.setBackground(new Color(0, 51, 153));
        avaliacoes.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_avaliacoesMouseExited

    private void avalIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avalIconMouseClicked

    }//GEN-LAST:event_avalIconMouseClicked

    private void avalIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avalIconMouseEntered
        avalTab.setBackground(new Color(51, 0, 102));
        avaliacoes.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_avalIconMouseEntered

    private void avalIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avalIconMouseExited
        avaliacoes.setBackground(new Color(0, 51, 153));
        avalTab.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_avalIconMouseExited

    private void avalTabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avalTabMouseEntered

    }//GEN-LAST:event_avalTabMouseEntered

    private void avalTabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avalTabMouseExited

    }//GEN-LAST:event_avalTabMouseExited
    
    public void fillAvalTable(){
        try {
            DefaultTableModel modelo = (DefaultTableModel)avalTable.getModel();
            modelo.setNumRows(0);
            AvaliacaoController control = new AvaliacaoController(); 
            NotaController nControl = new NotaController();
            for(int i = 0; i < nControl.ListAll(Login.CODIGO_DO_PROFESSOR).size(); i++){
                String data[] = {control.ListTable(Login.CODIGO_DO_PROFESSOR).get(0).getNomeAvaliacao(),
                control.ListTable(Login.CODIGO_DO_PROFESSOR).get(0).getData(),
                control.ListTable(Login.CODIGO_DO_PROFESSOR).get(0).getNomeDisciplina(),
                String.valueOf(nControl.ListAll(Login.CODIGO_DO_PROFESSOR).get(i).getNota()),
                nControl.ListAll(Login.CODIGO_DO_PROFESSOR).get(i).getNomeEstudante()};
                DefaultTableModel model = (DefaultTableModel)avalTable.getModel();
                model.addRow(data);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizarLista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLista3ActionPerformed
        fillAvalTable();
    }//GEN-LAST:event_atualizarLista3ActionPerformed

    private void atualizarAvalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAvalBtnActionPerformed
        JOptionPane.showMessageDialog(null, "A NOTA JA ESTA NO SISTEMA KKKKKKSJDHGSH"
                + "GFAHFASFJASLFLKASJFLKSAJKFJASKJFKASHKFHASFHIJHAGIOHIJGTIHJFKLSKLLDKSLDSDLKKLDSKLD");
    }//GEN-LAST:event_atualizarAvalBtnActionPerformed

    private void efectuarAvalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectuarAvalBtnActionPerformed
        try {
            DisciplinaController dControl = new DisciplinaController();
            Avaliacao avaliacao = new Avaliacao(JOptionPane.showInputDialog("Nome da Avaliacao: "), 
            new Date(System.currentTimeMillis()).toString(), dControl.codigoDisciplina(Login.CODIGO_DO_PROFESSOR), Login.CODIGO_DO_PROFESSOR);
            AvaliacaoController control = new AvaliacaoController();
            if(control.save(avaliacao)){
                EstudanteController eControl = new EstudanteController();
                for (int i = 0; i<eControl.showAll().size(); i++){
                    NotaController nControl = new NotaController();
                    Nota nota = new Nota(Double.parseDouble(JOptionPane.showInputDialog("Nota do Estudante: "+eControl.showAll().get(i).getNome())),
                    eControl.showAll().get(i).getNome(), dControl.codigoDisciplina(Login.CODIGO_DO_PROFESSOR),Login.CODIGO_DO_PROFESSOR);
                    nControl.createTable();
                    if(!nControl.save(nota)){
                        JOptionPane.showMessageDialog(null, "ERRO");break;
                    }
                }
                JOptionPane.showMessageDialog(null, "Notas Registadas");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TeacherDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_efectuarAvalBtnActionPerformed

    private void sairIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairIconMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_sairIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane EstJScrollPane;
    private javax.swing.JScrollPane EstJScrollPane3;
    private javax.swing.JButton atualizarAvalBtn;
    private javax.swing.JButton atualizarLista;
    private javax.swing.JButton atualizarLista3;
    private javax.swing.JLabel avalIcon;
    private javax.swing.JPanel avalTab;
    private javax.swing.JTable avalTable;
    private java.awt.Label avaliacoes;
    private javax.swing.JButton efectuarAvalBtn;
    private javax.swing.JTable estTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.Label sair;
    private javax.swing.JLabel sairIcon;
    private javax.swing.JPanel sairTab;
    private javax.swing.JLabel savaLife;
    private javax.swing.JLabel userLogo;
    // End of variables declaration//GEN-END:variables
}
